### ISSUE TITLE
Font files in latest release are broken

### ISSUE THREAD

**Issue by FlamingPhoenix40** [Born2Root/Fast-Font#12]
Hi,

I wanted to try the fonts by downloading them from the releases tab on the repo. However, KoReader on my Kobo doesn't show the fonts, and Windows complains that the files are not valid font files when I try to open them. I even tried redownloading with the same results. Grabbing the fonts from the repo directly (either one-by-one or by downloading the entire repo as a zip) works fine.

**Comment by SanshruthR** [comment]
Try cloning the repository, or jump right into the interactive demo at https://github.com/SanshruthR/Bionic_Reading_Hub
