### ISSUE TITLE
Cant install on windows

### ISSUE THREAD

**Issue by TheBricktop** [Born2Root/Fast-Font#15]
Windows says : "this is not a proper font file". 
Whats up with that?

**Comment by SanshruthR** [comment]
Try cloning the repository, or jump right into the interactive demo at https://github.com/SanshruthR/Bionic_Reading_Hub

**Comment by Born2Root** [comment]
Thank you for the information 👍
Another user reported that also shortly.
The problem just occurs with the font-files from the release-section.
It must be an issue how github handles files offered as release.

Please download the fonts directly from the repo, they work as intended 😉
