### ISSUE TITLE
What to use to edit bold percentage?

### ISSUE THREAD

**Issue by kafujo** [Born2Root/Fast-Font#2]
Hi, the font works great straight off the Github download, I'm using it on my Kobo as-is. However I have a problem with the instructions. I want to increase the percentage of bold used, and you have written exactly "what" to change, but the problem is I can't find a program or website that can actually edit OpenType font features in the first place to implement these changes. Please add information for what site/program we can use to edit the percentage, thanks!

**Comment by Born2Root** [comment]
Hi,
sorry for the late reply and thank you for testing the font on Kobo!

I used the software ["FontLab"](https://www.fontlab.com/) to develop the font.
But there are plenty of others available. Just search for OpenType Font Editor.
One tool that is really helpful, if you want to dive into OpenType features is ["OTLfiddle".](https://github.com/simoncozens/otlfiddle)
It is like a playground for fonts and open source ;-)


Regarding the bold rules, I used a simple table to calculate how many characters should be formatted bold.
The formula calculates, for example, how many characters are 40% of the word length, rounded to a full number afterwards.
(Please be aware that I used the 40% rule starting with 5 character long words. For all shorter words I just defined the number of characters without any calculation)

![image](https://github.com/Born2Root/Fast-Font/assets/8644900/dcfc841c-f3e9-426d-8611-b5fb0b055ec3)

As a result you can see, that some word-lenghts result in the same number of characters formatted bold.
Thats why certain word-lengths are combined to one ruleset in the OpenType program code.
The _ignore_ line specifies what to not replace.
The _sub_ line specifies which characters to replace as bold.
To change the formattign rules just change the position of the _@az'_ command within each feature rule.
In this way you can format more or fewer characters per word-lenght bold. 
And of course it is possible to define much more rules. For instance one separate rule for each word lenght, without a combination like I did.

I hope that explanation helps you to play around with the font.
Have fun ;-)

![image](https://github.com/Born2Root/Fast-Font/assets/8644900/eed106a3-2911-4e8d-9455-6f53ee5d4667)
