### ISSUE TITLE
Fast Serif : bug with ff, fi, fl

### ISSUE THREAD

**Issue by florianthomi** [Born2Root/Fast-Font#6]
Hi,

I find a bug with the serif font, when there's a double ff or fi or fl (and maybe other association). When these letter combinations appear, the following letters are considered to be a new word and are highlighted in bold. Here are a few examples

![image](https://github.com/Born2Root/Fast-Font/assets/51330023/5c8dab99-c349-425c-aff2-d7135c143d2e)

**Comment by Born2Root** [comment]
For myself I was just using the standard font, so I did not ran into this issue yet.
Therefore thank you very much for the bug report, and sorry for the late reply.

Regarding a technical explanation:
The combination of ff or fi, etc. is a classic ligature feature of serif open type fonts. It combines letters to one new glyph.
You can see that very nice in your screenshot, that the two ff are combined to one single character that looks way better, than two single f characters beside each other.
In the combination with our fast-reading feature this leads unfortunately to the unintended behaviour of recognizing this new character as a new word.

I fixed the font just by removing the whole ligature feature.
You can download the new version from the repo.

Have fun ;-)

**Comment by Born2Root** [comment]
Solved and fixed font updated in the repo.
