### ISSUE TITLE
(2) Adding fast-font type features to other fonts family

### ISSUE THREAD

**Issue by kaylosilva** [Born2Root/Fast-Font#7]
Hi, Can you help me convert these fonts to bionic reading? I could not do it.
https://drive.google.com/drive/folders/1eHvBDR_sx360sAPpd9hSqI_9HTQq4KZM?usp=sharing

**Comment by Born2Root** [comment]
Hi,
sorry for the late reply.
Yes for sure, nearly every font can be turned into a bionic-reading version.

Unfortunately you only uploaded the "standard" and "itallic" version of the fonts.
To turn those into a bionic-version we also need the "bold" versions.
This means the "SuperBlue Bold" and "SuperBlue Bold Italic" fontfiles are needed.

I searched for these versions online, but realized that these are commercial fonts that cost money and are copyright protected.
[https://fonts.adobe.com/fonts/superblue](https://fonts.adobe.com/fonts/superblue)

If you are the owner of the font or upload me the fonts we can talk about converting them to the bionic-version.
As they are copyright protected by  Sean Donohoe, I will not be able to release them afterwards for everyone on Github.
Thats why the fonts that I used for the project are free open-source fonts.

**Comment by kaylosilva** [comment]
sorry for the late reply! Uploaded "SuperBlue Bold" and "SuperBlue Bold Italic"

**Comment by Born2Root** [comment]
... I generated the Fast-Reading version of the Font.
Have fun ;-)

https://www.dropbox.com/scl/fi/th93dj67vefkb74wxpt0v/SuperBlue-Fast.ttf?rlkey=cywd61hhh2ecit2q76q6fj2sw&st=gqele08d&dl=0

**Comment by Born2Root** [comment]
Hi, sorry for the late reply.
I also added the Itallic version to the [Dropbox](https://www.dropbox.com/scl/fo/f5dy3y1f5tny6fe0hakg3/AEcKsKjVXJFQTFSmJpiEuXI?rlkey=rygvotwvwrqhezva9r6qw7hyi&st=gr5h4i1z&dl=0) 😉
